### ISSUE TITLE
build wrf-python for python 3.9

### ISSUE THREAD

**Issue by mathause** [conda-forge/wrf-python-feedstock#54]
Currently wrf-python is not available for python 3.9 (see `conda search -c conda-forge wrf-python`). #52 tries to address this but failed - it might just work if you re-render it now? I think all dependencies are available.

**Comment by honnorat** [comment]
Well, v1.3.2.6 might solve this issue.  
https://github.com/NCAR/wrf-python/releases/tag/1.3.2.6

**Comment by honnorat** [comment]
Yes indeed.
https://github.com/conda-forge/wrf-python-feedstock/pull/55/checks

Thank you @erogluorhan !

**Comment by erogluorhan** [comment]
@honnorat , no problem! Thank you, too,  for remind this issue to me! I think we can happily close this now.
